// Code generated by the Encore 1.57.11 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly admin: admin.ServiceClient
    public readonly agentapi: agentapi.ServiceClient
    public readonly analytics: analytics.ServiceClient
    public readonly catalog: catalog.ServiceClient
    public readonly checkout: checkout.ServiceClient
    public readonly merchants: merchants.ServiceClient
    public readonly orders: orders.ServiceClient
    public readonly policies: policies.ServiceClient
    public readonly readiness: readiness.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.admin = new admin.ServiceClient(base)
        this.agentapi = new agentapi.ServiceClient(base)
        this.analytics = new analytics.ServiceClient(base)
        this.catalog = new catalog.ServiceClient(base)
        this.checkout = new checkout.ServiceClient(base)
        this.merchants = new merchants.ServiceClient(base)
        this.orders = new orders.ServiceClient(base)
        this.policies = new policies.ServiceClient(base)
        this.readiness = new readiness.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getMerchantDetails as api_admin_get_merchant_details_getMerchantDetails } from "~backend/admin/get_merchant_details";
import { getSystemHealth as api_admin_get_system_health_getSystemHealth } from "~backend/admin/get_system_health";
import { listMerchants as api_admin_list_merchants_listMerchants } from "~backend/admin/list_merchants";
import { suspendMerchant as api_admin_suspend_merchant_suspendMerchant } from "~backend/admin/suspend_merchant";

export namespace admin {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getMerchantDetails = this.getMerchantDetails.bind(this)
            this.getSystemHealth = this.getSystemHealth.bind(this)
            this.listMerchants = this.listMerchants.bind(this)
            this.suspendMerchant = this.suspendMerchant.bind(this)
        }

        /**
         * Retrieves full merchant details for admin review.
         */
        public async getMerchantDetails(params: { id: string }): Promise<ResponseType<typeof api_admin_get_merchant_details_getMerchantDetails>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/merchants/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_get_merchant_details_getMerchantDetails>
        }

        /**
         * Returns system health status for all backend services.
         */
        public async getSystemHealth(): Promise<ResponseType<typeof api_admin_get_system_health_getSystemHealth>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/system/health`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_get_system_health_getSystemHealth>
        }

        /**
         * Lists all merchant organizations (admin only).
         */
        public async listMerchants(params: RequestType<typeof api_admin_list_merchants_listMerchants>): Promise<ResponseType<typeof api_admin_list_merchants_listMerchants>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
                status: params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/merchants`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_list_merchants_listMerchants>
        }

        /**
         * Suspends a merchant organization, disabling their access and public API.
         */
        public async suspendMerchant(params: { id: string }): Promise<ResponseType<typeof api_admin_suspend_merchant_suspendMerchant>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/merchants/${encodeURIComponent(params.id)}/suspend`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_suspend_merchant_suspendMerchant>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createCheckout as api_agentapi_create_checkout_createCheckout } from "~backend/agentapi/create_checkout";
import { getCheckout as api_agentapi_get_checkout_getCheckout } from "~backend/agentapi/get_checkout";
import { getOrderStatus as api_agentapi_get_order_status_getOrderStatus } from "~backend/agentapi/get_order_status";
import { getPublicMerchant as api_agentapi_get_public_merchant_getPublicMerchant } from "~backend/agentapi/get_public_merchant";
import { getPublicPolicies as api_agentapi_get_public_policies_getPublicPolicies } from "~backend/agentapi/get_public_policies";
import { getPublicProduct as api_agentapi_get_public_product_getPublicProduct } from "~backend/agentapi/get_public_product";
import { searchCatalog as api_agentapi_search_catalog_searchCatalog } from "~backend/agentapi/search_catalog";

export namespace agentapi {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createCheckout = this.createCheckout.bind(this)
            this.getCheckout = this.getCheckout.bind(this)
            this.getOrderStatus = this.getOrderStatus.bind(this)
            this.getPublicMerchant = this.getPublicMerchant.bind(this)
            this.getPublicPolicies = this.getPublicPolicies.bind(this)
            this.getPublicProduct = this.getPublicProduct.bind(this)
            this.searchCatalog = this.searchCatalog.bind(this)
        }

        /**
         * Creates a checkout session for an AI agent, validating stock and prices server-side.
         */
        public async createCheckout(params: RequestType<typeof api_agentapi_create_checkout_createCheckout>): Promise<ResponseType<typeof api_agentapi_create_checkout_createCheckout>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/v1/checkouts`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agentapi_create_checkout_createCheckout>
        }

        /**
         * Returns the current status of a checkout session.
         */
        public async getCheckout(params: { id: string }): Promise<ResponseType<typeof api_agentapi_get_checkout_getCheckout>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/v1/checkouts/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agentapi_get_checkout_getCheckout>
        }

        /**
         * Returns the current status of an order for tracking purposes.
         */
        public async getOrderStatus(params: { id: string }): Promise<ResponseType<typeof api_agentapi_get_order_status_getOrderStatus>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/v1/orders/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agentapi_get_order_status_getOrderStatus>
        }

        /**
         * Returns public merchant information for AI agents.
         */
        public async getPublicMerchant(params: { merchantId: string }): Promise<ResponseType<typeof api_agentapi_get_public_merchant_getPublicMerchant>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/v1/merchants/${encodeURIComponent(params.merchantId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agentapi_get_public_merchant_getPublicMerchant>
        }

        /**
         * Returns all active merchant policies for AI agent consumption.
         */
        public async getPublicPolicies(params: RequestType<typeof api_agentapi_get_public_policies_getPublicPolicies>): Promise<ResponseType<typeof api_agentapi_get_public_policies_getPublicPolicies>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                merchantId: params.merchantId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/v1/policies`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agentapi_get_public_policies_getPublicPolicies>
        }

        /**
         * Returns public product details for AI agent consumption.
         */
        public async getPublicProduct(params: { productId: string }): Promise<ResponseType<typeof api_agentapi_get_public_product_getPublicProduct>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/v1/products/${encodeURIComponent(params.productId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agentapi_get_public_product_getPublicProduct>
        }

        /**
         * Searches the agent-readable product catalog with optional filters.
         */
        public async searchCatalog(params: RequestType<typeof api_agentapi_search_catalog_searchCatalog>): Promise<ResponseType<typeof api_agentapi_search_catalog_searchCatalog>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                category:    params.category,
                limit:       params.limit === undefined ? undefined : String(params.limit),
                maxPrice:    params.maxPrice === undefined ? undefined : String(params.maxPrice),
                merchantId:  params.merchantId,
                minPrice:    params.minPrice === undefined ? undefined : String(params.minPrice),
                offset:      params.offset === undefined ? undefined : String(params.offset),
                q:           params.q,
                stockStatus: params.stockStatus,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/v1/catalog/search`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agentapi_search_catalog_searchCatalog>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getAgentStats as api_analytics_get_agent_stats_getAgentStats } from "~backend/analytics/get_agent_stats";
import { getDashboardMetrics as api_analytics_get_dashboard_metrics_getDashboardMetrics } from "~backend/analytics/get_dashboard_metrics";
import { trackEvent as api_analytics_track_event_trackEvent } from "~backend/analytics/track_event";

export namespace analytics {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getAgentStats = this.getAgentStats.bind(this)
            this.getDashboardMetrics = this.getDashboardMetrics.bind(this)
            this.trackEvent = this.trackEvent.bind(this)
        }

        /**
         * Returns per-agent request statistics for a merchant.
         */
        public async getAgentStats(params: RequestType<typeof api_analytics_get_agent_stats_getAgentStats>): Promise<ResponseType<typeof api_analytics_get_agent_stats_getAgentStats>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                days:           params.days === undefined ? undefined : String(params.days),
                organizationId: params.organizationId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/agents`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_get_agent_stats_getAgentStats>
        }

        /**
         * Returns dashboard analytics metrics for a merchant.
         */
        public async getDashboardMetrics(params: RequestType<typeof api_analytics_get_dashboard_metrics_getDashboardMetrics>): Promise<ResponseType<typeof api_analytics_get_dashboard_metrics_getDashboardMetrics>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                days:           params.days === undefined ? undefined : String(params.days),
                organizationId: params.organizationId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/dashboard`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_get_dashboard_metrics_getDashboardMetrics>
        }

        /**
         * Tracks an agent or API request event for analytics purposes.
         */
        public async trackEvent(params: RequestType<typeof api_analytics_track_event_trackEvent>): Promise<ResponseType<typeof api_analytics_track_event_trackEvent>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/track`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_track_event_trackEvent>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createDemoProducts as api_catalog_create_demo_products_createDemoProducts } from "~backend/catalog/create_demo_products";
import { createProduct as api_catalog_create_product_createProduct } from "~backend/catalog/create_product";
import { createVariant as api_catalog_create_variant_createVariant } from "~backend/catalog/create_variant";
import { deleteProduct as api_catalog_delete_product_deleteProduct } from "~backend/catalog/delete_product";
import { getProduct as api_catalog_get_product_getProduct } from "~backend/catalog/get_product";
import { importCSV as api_catalog_import_csv_importCSV } from "~backend/catalog/import_csv";
import { listProducts as api_catalog_list_products_listProducts } from "~backend/catalog/list_products";
import { publishCatalog as api_catalog_publish_catalog_publishCatalog } from "~backend/catalog/publish_catalog";
import { updateProduct as api_catalog_update_product_updateProduct } from "~backend/catalog/update_product";
import { updateVariant as api_catalog_update_variant_updateVariant } from "~backend/catalog/update_variant";

export namespace catalog {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createDemoProducts = this.createDemoProducts.bind(this)
            this.createProduct = this.createProduct.bind(this)
            this.createVariant = this.createVariant.bind(this)
            this.deleteProduct = this.deleteProduct.bind(this)
            this.getProduct = this.getProduct.bind(this)
            this.importCSV = this.importCSV.bind(this)
            this.listProducts = this.listProducts.bind(this)
            this.publishCatalog = this.publishCatalog.bind(this)
            this.updateProduct = this.updateProduct.bind(this)
            this.updateVariant = this.updateVariant.bind(this)
        }

        /**
         * Creates sample Indonesian merchant products for demonstration and testing purposes.
         */
        public async createDemoProducts(params: RequestType<typeof api_catalog_create_demo_products_createDemoProducts>): Promise<ResponseType<typeof api_catalog_create_demo_products_createDemoProducts>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/catalog/demo`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_catalog_create_demo_products_createDemoProducts>
        }

        /**
         * Creates a new product in the merchant's catalog.
         */
        public async createProduct(params: RequestType<typeof api_catalog_create_product_createProduct>): Promise<ResponseType<typeof api_catalog_create_product_createProduct>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_catalog_create_product_createProduct>
        }

        /**
         * Adds a new variant to an existing product.
         */
        public async createVariant(params: RequestType<typeof api_catalog_create_variant_createVariant>): Promise<ResponseType<typeof api_catalog_create_variant_createVariant>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                attributes:        params.attributes,
                barcode:           params.barcode,
                currency:          params.currency,
                imageUrl:          params.imageUrl,
                listAmount:        params.listAmount,
                organizationId:    params.organizationId,
                quantityAvailable: params.quantityAvailable,
                saleAmount:        params.saleAmount,
                sku:               params.sku,
                title:             params.title,
                weightGrams:       params.weightGrams,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products/${encodeURIComponent(params.id)}/variants`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_catalog_create_variant_createVariant>
        }

        /**
         * Archives (soft-deletes) a product from the catalog.
         */
        public async deleteProduct(params: { id: string }): Promise<ResponseType<typeof api_catalog_delete_product_deleteProduct>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_catalog_delete_product_deleteProduct>
        }

        /**
         * Retrieves a product with all its variants, prices, and inventory.
         */
        public async getProduct(params: { id: string }): Promise<ResponseType<typeof api_catalog_get_product_getProduct>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_catalog_get_product_getProduct>
        }

        /**
         * Validates and imports product data from CSV format.
         */
        public async importCSV(params: RequestType<typeof api_catalog_import_csv_importCSV>): Promise<ResponseType<typeof api_catalog_import_csv_importCSV>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/catalog/import`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_catalog_import_csv_importCSV>
        }

        /**
         * Lists all products for a merchant organization with optional filters.
         */
        public async listProducts(params: RequestType<typeof api_catalog_list_products_listProducts>): Promise<ResponseType<typeof api_catalog_list_products_listProducts>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                category:       params.category,
                limit:          params.limit === undefined ? undefined : String(params.limit),
                offset:         params.offset === undefined ? undefined : String(params.offset),
                organizationId: params.organizationId,
                search:         params.search,
                status:         params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_catalog_list_products_listProducts>
        }

        /**
         * Publishes all draft products in a merchant's catalog, making them publicly discoverable.
         */
        public async publishCatalog(params: RequestType<typeof api_catalog_publish_catalog_publishCatalog>): Promise<ResponseType<typeof api_catalog_publish_catalog_publishCatalog>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/catalog/publish`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_catalog_publish_catalog_publishCatalog>
        }

        /**
         * Updates a product's metadata and status.
         */
        public async updateProduct(params: RequestType<typeof api_catalog_update_product_updateProduct>): Promise<ResponseType<typeof api_catalog_update_product_updateProduct>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                attributes:      params.attributes,
                brand:           params.brand,
                category:        params.category,
                description:     params.description,
                primaryImageUrl: params.primaryImageUrl,
                productUrl:      params.productUrl,
                status:          params.status,
                title:           params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_catalog_update_product_updateProduct>
        }

        /**
         * Updates a product variant's details, price, and inventory.
         */
        public async updateVariant(params: RequestType<typeof api_catalog_update_variant_updateVariant>): Promise<ResponseType<typeof api_catalog_update_variant_updateVariant>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                attributes:         params.attributes,
                availabilityStatus: params.availabilityStatus,
                imageUrl:           params.imageUrl,
                listAmount:         params.listAmount,
                quantityAvailable:  params.quantityAvailable,
                saleAmount:         params.saleAmount,
                sku:                params.sku,
                status:             params.status,
                title:              params.title,
                weightGrams:        params.weightGrams,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/variants/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_catalog_update_variant_updateVariant>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createCheckoutSession as api_checkout_create_checkout_session_createCheckoutSession } from "~backend/checkout/create_checkout_session";
import { getCheckoutSession as api_checkout_get_checkout_session_getCheckoutSession } from "~backend/checkout/get_checkout_session";

export namespace checkout {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createCheckoutSession = this.createCheckoutSession.bind(this)
            this.getCheckoutSession = this.getCheckoutSession.bind(this)
        }

        /**
         * Creates a new checkout session, validating prices and stock server-side.
         */
        public async createCheckoutSession(params: RequestType<typeof api_checkout_create_checkout_session_createCheckoutSession>): Promise<ResponseType<typeof api_checkout_create_checkout_session_createCheckoutSession>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/checkout`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_checkout_create_checkout_session_createCheckoutSession>
        }

        /**
         * Retrieves a checkout session by its public ID.
         */
        public async getCheckoutSession(params: { publicId: string }): Promise<ResponseType<typeof api_checkout_get_checkout_session_getCheckoutSession>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/checkout/${encodeURIComponent(params.publicId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_checkout_get_checkout_session_getCheckoutSession>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createOrganization as api_merchants_create_organization_createOrganization } from "~backend/merchants/create_organization";
import { getMerchantProfile as api_merchants_get_merchant_profile_getMerchantProfile } from "~backend/merchants/get_merchant_profile";
import { getOrganization as api_merchants_get_organization_getOrganization } from "~backend/merchants/get_organization";
import { updateMerchantProfile as api_merchants_update_merchant_profile_updateMerchantProfile } from "~backend/merchants/update_merchant_profile";
import { updateOrganization as api_merchants_update_organization_updateOrganization } from "~backend/merchants/update_organization";

export namespace merchants {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createOrganization = this.createOrganization.bind(this)
            this.getMerchantProfile = this.getMerchantProfile.bind(this)
            this.getOrganization = this.getOrganization.bind(this)
            this.updateMerchantProfile = this.updateMerchantProfile.bind(this)
            this.updateOrganization = this.updateOrganization.bind(this)
        }

        /**
         * Creates a new merchant organization workspace.
         */
        public async createOrganization(params: RequestType<typeof api_merchants_create_organization_createOrganization>): Promise<ResponseType<typeof api_merchants_create_organization_createOrganization>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/organizations`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_merchants_create_organization_createOrganization>
        }

        /**
         * Retrieves a merchant's public profile.
         */
        public async getMerchantProfile(params: { id: string }): Promise<ResponseType<typeof api_merchants_get_merchant_profile_getMerchantProfile>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/merchants/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_merchants_get_merchant_profile_getMerchantProfile>
        }

        /**
         * Retrieves an organization by its slug.
         */
        public async getOrganization(params: { slug: string }): Promise<ResponseType<typeof api_merchants_get_organization_getOrganization>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/organizations/${encodeURIComponent(params.slug)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_merchants_get_organization_getOrganization>
        }

        /**
         * Updates a merchant's profile information.
         */
        public async updateMerchantProfile(params: RequestType<typeof api_merchants_update_merchant_profile_updateMerchantProfile>): Promise<ResponseType<typeof api_merchants_update_merchant_profile_updateMerchantProfile>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                addressJson:  params.addressJson,
                description:  params.description,
                displayName:  params.displayName,
                legalName:    params.legalName,
                publicStatus: params.publicStatus,
                supportEmail: params.supportEmail,
                supportPhone: params.supportPhone,
                supportUrl:   params.supportUrl,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/merchants/${encodeURIComponent(params.id)}/profile`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_merchants_update_merchant_profile_updateMerchantProfile>
        }

        /**
         * Updates an organization's details.
         */
        public async updateOrganization(params: RequestType<typeof api_merchants_update_organization_updateOrganization>): Promise<ResponseType<typeof api_merchants_update_organization_updateOrganization>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                logoUrl:    params.logoUrl,
                name:       params.name,
                status:     params.status,
                websiteUrl: params.websiteUrl,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/organizations/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_merchants_update_organization_updateOrganization>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getOrder as api_orders_get_order_getOrder } from "~backend/orders/get_order";
import { listOrders as api_orders_list_orders_listOrders } from "~backend/orders/list_orders";
import { updateFulfillmentStatus as api_orders_update_fulfillment_status_updateFulfillmentStatus } from "~backend/orders/update_fulfillment_status";

export namespace orders {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getOrder = this.getOrder.bind(this)
            this.listOrders = this.listOrders.bind(this)
            this.updateFulfillmentStatus = this.updateFulfillmentStatus.bind(this)
        }

        /**
         * Retrieves a single order with all its items.
         */
        public async getOrder(params: { id: string }): Promise<ResponseType<typeof api_orders_get_order_getOrder>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/orders/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_orders_get_order_getOrder>
        }

        /**
         * Lists all orders for a merchant with optional status filters.
         */
        public async listOrders(params: RequestType<typeof api_orders_list_orders_listOrders>): Promise<ResponseType<typeof api_orders_list_orders_listOrders>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                fulfillmentStatus: params.fulfillmentStatus,
                limit:             params.limit === undefined ? undefined : String(params.limit),
                offset:            params.offset === undefined ? undefined : String(params.offset),
                organizationId:    params.organizationId,
                paymentStatus:     params.paymentStatus,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/orders`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_orders_list_orders_listOrders>
        }

        /**
         * Updates the fulfillment status of an order.
         */
        public async updateFulfillmentStatus(params: RequestType<typeof api_orders_update_fulfillment_status_updateFulfillmentStatus>): Promise<ResponseType<typeof api_orders_update_fulfillment_status_updateFulfillmentStatus>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                carrier:           params.carrier,
                fulfillmentStatus: params.fulfillmentStatus,
                trackingNumber:    params.trackingNumber,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/orders/${encodeURIComponent(params.id)}/fulfillment`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_orders_update_fulfillment_status_updateFulfillmentStatus>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getPolicy as api_policies_get_policy_getPolicy } from "~backend/policies/get_policy";
import { listPolicies as api_policies_list_policies_listPolicies } from "~backend/policies/list_policies";
import { upsertPolicy as api_policies_upsert_policy_upsertPolicy } from "~backend/policies/upsert_policy";

export namespace policies {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getPolicy = this.getPolicy.bind(this)
            this.listPolicies = this.listPolicies.bind(this)
            this.upsertPolicy = this.upsertPolicy.bind(this)
        }

        public async getPolicy(params: RequestType<typeof api_policies_get_policy_getPolicy>): Promise<ResponseType<typeof api_policies_get_policy_getPolicy>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                organizationId: params.organizationId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/policies/${encodeURIComponent(params.policyType)}`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_policies_get_policy_getPolicy>
        }

        /**
         * Lists all policies for a merchant organization.
         */
        public async listPolicies(params: RequestType<typeof api_policies_list_policies_listPolicies>): Promise<ResponseType<typeof api_policies_list_policies_listPolicies>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                organizationId: params.organizationId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/policies`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_policies_list_policies_listPolicies>
        }

        /**
         * Creates or updates a merchant policy of a given type.
         */
        public async upsertPolicy(params: RequestType<typeof api_policies_upsert_policy_upsertPolicy>): Promise<ResponseType<typeof api_policies_upsert_policy_upsertPolicy>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/policies`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_policies_upsert_policy_upsertPolicy>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getReadinessScore as api_readiness_get_readiness_score_getReadinessScore } from "~backend/readiness/get_readiness_score";

export namespace readiness {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getReadinessScore = this.getReadinessScore.bind(this)
        }

        /**
         * Calculates and returns the agent-readiness score for a merchant.
         */
        public async getReadinessScore(params: { organizationId: string }): Promise<ResponseType<typeof api_readiness_get_readiness_score_getReadinessScore>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/readiness/${encodeURIComponent(params.organizationId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_readiness_get_readiness_score_getReadinessScore>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.57.11)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        let response: Response;
        if ((window as any).__cl_backend_offline) {
            return new Response(JSON.stringify({}), { status: 200, headers: { "Content-Type": "application/json" } });
        }
        try {
            response = await this.fetcher(this.baseURL+path+queryString, init);
        } catch (err) {
            (window as any).__cl_backend_offline = true;
            return new Response(JSON.stringify({}), { status: 200, headers: { "Content-Type": "application/json" } });
        }

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

if (typeof window !== "undefined" && !import.meta.env.VITE_ENABLE_LIVE_BACKEND) {
  (window as any).__cl_backend_offline = true;
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
